/**
 * Database Models for Todo Management Application
 * Plain TypeScript types for entity modeling
 */

// ============================================================================
// Enums
// ============================================================================

/**
 * Priority levels in ascending order of importance
 */
export type Priority = "low" | "medium" | "high" | "urgent";

/**
 * Status values as stored in the database
 * Note: "due" is never stored, only calculated on-demand
 */
export type StoredStatus = "initial" | "complete";

/**
 * Status values as returned to clients (includes calculated "due")
 */
export type CalculatedStatus = "initial" | "complete" | "due";

// ============================================================================
// Entity Models
// ============================================================================

/**
 * Todo Entity - Database representation
 * This is the exact structure stored in the database
 */
export type TodoEntity = {
  /**
   * Unique identifier (UUID v4)
   * Generated by the system on creation
   */
  id: string;

  /**
   * Todo title
   * Required, max 100 characters
   */
  title: string;

  /**
   * Optional detailed description
   * Max 1000 characters, nullable
   */
  description: string | null;

  /**
   * Stored status (never "due")
   * Only "initial" or "complete" are persisted
   */
  status: StoredStatus;

  /**
   * Optional due date (date only, no time component)
   * Format: YYYY-MM-DD
   * Nullable - null means no due date
   */
  dueDate: string | null;

  /**
   * Priority level
   * Required, defaults to "medium" on creation
   */
  priority: Priority;

  /**
   * Creation timestamp (UTC)
   * Automatically set on creation, immutable
   */
  createdAt: Date;

  /**
   * Last modification timestamp (UTC)
   * Automatically updated on successful changes
   */
  modifiedAt: Date;
};

/**
 * Todo DTO - Data Transfer Object
 * This is what gets returned to clients with calculated status
 */
export type TodoDTO = {
  id: string;
  title: string;
  description: string | null;
  status: CalculatedStatus; // Can be "due" (calculated)
  dueDate: string | null;
  priority: Priority;
  createdAt: string; // ISO 8601 string for API
  modifiedAt: string; // ISO 8601 string for API
};

// ============================================================================
// Input Models for Database Operations
// ============================================================================

/**
 * Input for creating a new todo
 * ID and timestamps are generated by the system
 */
export type CreateTodoInput = {
  title: string;
  description: string | null;
  dueDate: string | null;
  priority: Priority;
};

/**
 * Input for updating a todo (partial update)
 * All fields are optional except the ID
 */
export type UpdateTodoInput = {
  id: string;
  title?: string;
  description?: string | null;
  dueDate?: string | null;
  status?: StoredStatus;
  priority?: Priority;
};

/**
 * Input for bulk status update
 */
export type BulkUpdateStatusInput = {
  ids: string[];
  status: StoredStatus;
};

/**
 * Input for bulk delete
 */
export type BulkDeleteInput = {
  ids: string[];
};

// ============================================================================
// Filter Models for Database Queries
// ============================================================================

/**
 * Status filter operators
 */
export type StatusFilter = {
  equals?: CalculatedStatus;
  notEquals?: CalculatedStatus;
};

/**
 * Priority filter operators
 */
export type PriorityFilter = {
  equals?: Priority;
  notEquals?: Priority;
};

/**
 * Due date filter operators
 */
export type DueDateFilter = {
  before?: string;
  after?: string;
  notBefore?: string;
  notAfter?: string;
};

/**
 * String filter operators (case-insensitive)
 */
export type StringFilter = {
  contains?: string;
  notContains?: string;
};

/**
 * Complete filter criteria for querying todos
 */
export type TodoFilterCriteria = {
  status?: StatusFilter;
  priority?: PriorityFilter;
  dueDate?: DueDateFilter;
  title?: StringFilter;
  description?: StringFilter;
};

// ============================================================================
// Repository Result Types
// ============================================================================

/**
 * Result of a database operation that may succeed or fail
 */
export type RepositoryResult<T> =
  | { success: true; data: T }
  | { success: false; error: RepositoryError };

/**
 * Repository-level errors
 */
export type RepositoryError = {
  code: RepositoryErrorCode;
  message: string;
  details?: Record<string, unknown>;
};

/**
 * Repository error codes
 */
export type RepositoryErrorCode =
  | "NOT_FOUND"
  | "CONSTRAINT_VIOLATION"
  | "TRANSACTION_FAILED"
  | "DATABASE_ERROR";

// ============================================================================
// Query Results
// ============================================================================

/**
 * Paginated result (for future extension)
 * Not used in current version but included for schema completeness
 */
export type PaginatedResult<T> = {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
};

// ============================================================================
// Storage Configuration Types
// ============================================================================

/**
 * Configuration for in-memory cache with file persistence
 */
export type CacheConfig = {
  filePath: string; // JSON file path for persistence
  lockRetries?: number; // number of retry attempts, default 5
  retryBackoff?: number[]; // backoff intervals in ms, default [50, 100, 200, 400, 800]
  prettyPrint?: boolean; // format JSON with indentation, default false
  validateOnStartup?: boolean; // validate file on load, default false (MVP)
};

// ============================================================================
// Utility Types
// ============================================================================

/**
 * JSON file structure (key-value store)
 * Key: UUID string
 * Value: TodoEntity
 */
export type TodosFileContent = Record<string, TodoEntity>;

/**
 * In-memory cache structure (same as file format)
 */
export type TodosCache = Record<string, TodoEntity>;

/**
 * Cache lock state
 */
export type CacheLock = {
  locked: boolean;
  acquiredAt?: Date;
  operationId?: string;
};

/**
 * File operation result
 */
export type FileOperationResult<T> =
  | { success: true; data: T }
  | { success: false; error: FileOperationError };

/**
 * File operation errors
 */
export type FileOperationError = {
  code: FileErrorCode;
  message: string;
  details?: Record<string, unknown>;
};

/**
 * File error codes
 */
export type FileErrorCode =
  | "FILE_NOT_FOUND"
  | "FILE_READ_ERROR"
  | "FILE_WRITE_ERROR"
  | "FILE_LOCK_TIMEOUT"
  | "FILE_LOCK_ERROR"
  | "PARSE_ERROR"
  | "INVALID_FORMAT";

/**
 * Default file paths
 */
export const DEFAULT_FILE_PATH = "./data/todos.json" as const;
export const DEFAULT_BACKUP_PATH = "./data/backups" as const;

// ============================================================================
// Constants
// ============================================================================

/**
 * Default values for entity fields
 */
export const DEFAULT_VALUES = {
  priority: "medium" as Priority,
  status: "initial" as StoredStatus,
  description: null,
  dueDate: null,
} as const;

/**
 * Validation constraints
 */
export const CONSTRAINTS = {
  title: {
    minLength: 1,
    maxLength: 100,
  },
  description: {
    maxLength: 1000,
  },
  bulkOperation: {
    maxItems: 100,
  },
} as const;

/**
 * Valid enum values
 */
export const VALID_VALUES = {
  priority: ["low", "medium", "high", "urgent"] as const,
  storedStatus: ["initial", "complete"] as const,
  calculatedStatus: ["initial", "complete", "due"] as const,
} as const;

